INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (1, 1, 'Épilation visage', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (8, 2, ' Beauté mains', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (9, 2, 'Beauté pieds', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (10, 3, 'Soin visage', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (11, 3, 'Forfait - soins visage', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (12, 3, 'Forfait - soins visage : anti-âges', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (13, 4, ' Beauté des yeux', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (14, 4, 'Make up', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (15, 5, 'Soins corps', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (16, 5, 'Cures', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (17, 6, 'Visage', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (18, 7, ' Soins relax', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (19, 8, ' Épilations', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (20, 8, 'Soins', 1);
INSERT INTO ravoli_db.sub_category (sub_cat_id, sub_cat_parent, sub_cat_title, sub_cat_visible) VALUES (21, 1, 'Épilation corp', 1);