var annotated_dup =
[
    [ "AdminBar", "class_admin_bar.html", "class_admin_bar" ],
    [ "Categories_manager", "class_categories__manager.html", "class_categories__manager" ],
    [ "Category_class", "class_category__class.html", "class_category__class" ],
    [ "Dashboard", "class_dashboard.html", "class_dashboard" ],
    [ "DropdownMenu", "class_dropdown_menu.html", "class_dropdown_menu" ],
    [ "Event_class", "class_event__class.html", "class_event__class" ],
    [ "Events", "class_events.html", "class_events" ],
    [ "Events_manager", "class_events__manager.html", "class_events__manager" ],
    [ "Images", "class_images.html", "class_images" ],
    [ "Images_class", "class_images__class.html", "class_images__class" ],
    [ "Images_manager", "class_images__manager.html", "class_images__manager" ],
    [ "Newsletter", "class_newsletter.html", "class_newsletter" ],
    [ "Pages", "class_pages.html", "class_pages" ],
    [ "Prestation_class", "class_prestation__class.html", "class_prestation__class" ],
    [ "Prestations", "class_prestations.html", "class_prestations" ],
    [ "Prestations_manager", "class_prestations__manager.html", "class_prestations__manager" ],
    [ "Slide_class", "class_slide__class.html", "class_slide__class" ],
    [ "Slides", "class_slides.html", "class_slides" ],
    [ "Slides_manager", "class_slides__manager.html", "class_slides__manager" ],
    [ "SmartyLibrary", "class_smarty_library.html", "class_smarty_library" ],
    [ "SubCategories_manager", "class_sub_categories__manager.html", "class_sub_categories__manager" ],
    [ "SubCategory_class", "class_sub_category__class.html", "class_sub_category__class" ],
    [ "Subscribers_manager", "class_subscribers__manager.html", "class_subscribers__manager" ],
    [ "User_class", "class_user__class.html", "class_user__class" ],
    [ "Users", "class_users.html", "class_users" ],
    [ "Users_manager", "class_users__manager.html", "class_users__manager" ]
];